package org.apache.cayenne.serialization.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.serialization.persistent.Table2;

/**
 * Class _Table1 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Table1 extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String TABLE2S_PROPERTY = "table2s";

    public static final String PK_PK_COLUMN = "PK";

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToTable2s(Table2 obj) {
        addToManyTarget("table2s", obj, true);
    }
    public void removeFromTable2s(Table2 obj) {
        removeToManyTarget("table2s", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Table2> getTable2s() {
        return (List<Table2>)readProperty("table2s");
    }


}
