package org.apache.cayenne.serialization.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.serialization.persistent.Table1;

/**
 * Class _Table2 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Table2 extends CayenneDataObject {

    public static final String DATE_COLUMN_PROPERTY = "dateColumn";
    public static final String DOUBLE_COLUMN_PROPERTY = "doubleColumn";
    public static final String NAME_PROPERTY = "name";
    public static final String TABLE1_PROPERTY = "table1";

    public static final String PK_PK_COLUMN = "PK";

    public void setDateColumn(Date dateColumn) {
        writeProperty("dateColumn", dateColumn);
    }
    public Date getDateColumn() {
        return (Date)readProperty("dateColumn");
    }

    public void setDoubleColumn(Double doubleColumn) {
        writeProperty("doubleColumn", doubleColumn);
    }
    public Double getDoubleColumn() {
        return (Double)readProperty("doubleColumn");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setTable1(Table1 table1) {
        setToOneTarget("table1", table1, true);
    }

    public Table1 getTable1() {
        return (Table1)readProperty("table1");
    }


}
